obj-$(CONFIG_DIRECT_CHARGER) += direct_charger.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charger_sc.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charger_lvc.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charger_power_supply.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charger_error_handle.o

obj-$(CONFIG_LOADSWITCH) += loadswitch/
obj-$(CONFIG_SWITCHCAP) += switchcap/
obj-$(CONFIG_INA231_FOR_CHARGE) += ina231/
obj-$(CONFIG_OPA2333P_FOR_CHARGE) += opa2333p/
