
obj-$(CONFIG_NPU_DEVDRV) += platform/
obj-$(CONFIG_NPU_DEVDRV) += manager/
obj-$(CONFIG_NPU_DEVDRV) += device/
obj-$(CONFIG_NPU_HISI_ATF_SEVICES) +=services/atf/
obj-$(CONFIG_NPU_DEVDRV) += dfx/logdrv/
#obj-$(CONFIG_NPU_DEVDRV) += dfx/dbg/
obj-$(CONFIG_NPU_DEVDRV) += dfx/prof/


