# MD5: 0ffe0138cf16b1ebe9945c78a01b0e4f
CFG_TLPHY_CSU_DATA_SAMPLE_ENABLED      := YES
CFG_TLPHY_OM_RPT_ENABLED               := YES
CFG_TL_RFD_READ_ENABLED               := YES
CFG_UPHY_DESENSITIZATION_OFF           := YES
CFG_TLPHY_ASSERT_ENABLED                := YES
