ccflags-y += -Idrivers/media/huawei/camera/sensor
ccflags-y += -Idrivers/media/huawei/camera
ccflags-y += -Idrivers/media/huawei/camera/csi
ccflags-y += -Idrivers/media/huawei/camera/platform


obj-$(CONFIG_HUAWEI_CAMERA_USE_IMX386HYBIRD) += imx386hybird.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_IMX600HYBRID) += imx600hybrid.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_IMX319) += imx319.o

obj-$(CONFIG_HUAWEI_CAMERA_USE_CAMKIT) += hisensor.o

