#ifndef __BBOX_DIAGINFO_ID_DEF_H__
#define __BBOX_DIAGINFO_ID_DEF_H__ 
enum bbox_diaginfo_errid {
 SoC_DIAGINFO_START=925200000,
 L3_ECC_1BIT_ERROR = SoC_DIAGINFO_START,
 CPU_UP_FAIL,
 CPU_PANIC_INFO,
 NOC_FAULT_INFO,
 L3_ECC_2BIT_ERROR = 925201200,
 L3_ECC_BUS_ERROR,
 IOMCU_DIAG_INFO_HW_START = 925201600,
 SWING_DMD_FDUL_PW_ON = IOMCU_DIAG_INFO_HW_START,
 SWING_DMD_FDUL_PW_OFF,
 SWING_DMD_HWTS_PW_ON,
 SWING_DMD_HWTS_PW_OFF,
 SWING_DMD_AIC_PW_ON,
 SWING_DMD_AIC_PW_OFF,
 SWING_DMD_HWI_CREATE,
 SWING_DMD_HWI_DELETE,
 SWING_DMD_CAM_PW_ON,
 SWING_DMD_CAM_PW_OFF,
 SWING_DMD_CAM_IR_PW,
 SWING_DMD_CAM_TIMEOUT,
 IOMCU_DIAG_INFO_HW_END = 925201699,
 IOMCU_DIAG_INFO_SW_START = 925201700,
 SWING_DMD_BRIEF_CASE = IOMCU_DIAG_INFO_SW_START,
 SWING_DMD_INT1_AIC_ERR,
 SWING_DMD_INT1_TIMEOUT,
 SWING_DMD_INT1_BUS_ERR,
 SWING_DMD_INT7_BUS_ERR,
 SWING_DMD_FDUL_NOC,
 SWING_DMD_MODEL_LOAD,
 SWING_DMD_MODEL_UNLOAD,
 SWING_DMD_MODEL_RUN,
 SWING_DMD_AIC_KICK,
 SWING_DMD_CAMERA_INIT,
 SWING_DMD_CAMERA_RELEASE,
 SWING_DMD_SLEEP_FUSION = 925201714,
 IOMCU_DIAG_INFO_SW_END = 925201899,
 IOMCU_DIAG_INFO_MONITER_START = 925201900,
 IOMCU_DIAG_INFO_MONITER_END = 925201959,
 IOMCU_DIAG_INFO_RESERVED_START = 925201960,
 IOMCU_DIAG_INFO_RESERVED_END = 925201999,
 DDR_DIAGINFO_START=925202000,
 LPM3_DDR_FAIl = DDR_DIAGINFO_START,
 BBOX_DIAGINFO_END = 925299999
};
enum bbox_diaginfo_module {
 SoC_AP = 1,
 DSS,
 DDR,
 FDUL,
};
enum bbox_diaginfo_level {
 Critical = 1,
 Warning,
 INFO,
};
enum bbox_diaginfo_type {
 HW = 1,
 SW,
};
#endif
