EXTRA_CFLAGS += -Idrivers/hisi/slimbus/
EXTRA_CFLAGS += -Idrivers/devkit/audiokit/
EXTRA_CFLAGS += -Idrivers/hisi/hi64xx_dsp/
EXTRA_CFLAGS += -Isound/soc/codecs/hisi/

snd-soc-hi6405-objs :=hi6405.o
snd-soc-hi6405-kcontrol-objs :=hi6405_kcontrol.o
snd-soc-hi6405-resource-widget-objs :=hi6405_resource_widget.o
snd-soc-hi6405-path-widget-objs :=hi6405_path_widget.o
snd-soc-hi6405-switch-widget-objs :=hi6405_switch_widget.o
snd-soc-hi6405-route-objs :=hi6405_route.o

obj-y += snd-soc-hi6405.o
obj-y += snd-soc-hi6405-kcontrol.o
obj-y += snd-soc-hi6405-resource-widget.o
obj-y += snd-soc-hi6405-path-widget.o
obj-y += snd-soc-hi6405-switch-widget.o
obj-y += snd-soc-hi6405-route.o


