obj-$(CONFIG_HISI_SLOW_PATH_COUNT) += slowpath_count.o
obj-$(CONFIG_HISI_PMALLOC) += pmalloc.o
obj-$(CONFIG_DEBUG_HISI_PMALLOC) += test_pmalloc.o
obj-$(CONFIG_HISI_PAGE_TRACE) += mem_trace.o buddy_track.o
