#ifndef __NPU_PLATFORM_RESOURCE_H
#define __NPU_PLATFORM_RESOURCE_H

#define DEVDRV_PLAT_STREAM_MAX     (128)
#define DEVDRV_PLAT_EVENT_MAX      (256)
#define DEVDRV_PLAT_NOTIFY_MAX     (1024)
#define DEVDRV_PLAT_MODEL_MAX      (64)
#define DEVDRV_PLAT_AICORE_MAX     (1)
#define DEVDRV_PLAT_AICPU_MAX      (1)
#define DEVDRV_PLAT_CALC_SQ_MAX    (64)
#define DEVDRV_PLAT_CALC_SQ_DEPTH  (256)
#define DEVDRV_PLAT_CALC_CQ_MAX    (1)
#define DEVDRV_PLAT_CALC_CQ_DEPTH  (1024)
#define DEVDRV_PLAT_DFX_SQ_MAX     (4)
#define DEVDRV_PLAT_DFX_CQ_MAX     (10)
#define DEVDRV_PLAT_DFX_SQCQ_DEPTH (1024)
#define DEVDRV_PLAT_DOORBELL_STRIDE (4096)  /* stride 4KB */

#define TMP_lOG_BUF_SIZE    (0x80000)
#define TMP_LOG_BUFER_BASE  (0x302E0000)

#endif
